print* ,"	                              (_)(_)	"
print* ,"	                             /     \	"
print* ,"	                            /       |	"
print* ,"	                           /   \  * |	"
print* ,"	             ________     /    /\__/	"
print* ,"	     _      /        \   /    /	"
print* ,"	    / \    /  ____    \_/    /	"
print* ,"	   //\ \  /  /    \         /	"
print* ,"	   V  \ \/  /      \       /	"
end
